### ISSUE TITLE
Research report on Java developmet (Play framework)

### ISSUE THREAD

**Issue by iTech75** [awesome-possums/swe574#22]
Provide us the result of the R&D related to Java development and Play framework.

- [x] Why do we need Play framework?

**Comment by yusufyilmz** [comment]
:dart: 1h

**Comment by irmakcakmak** [comment]
:clock4: 
Reasons we picked Play framework are down below, directly from [https://www.playframework.com/](url)

Play is based on a lightweight, stateless, web-friendly architecture.

Built on Akka, Play provides predictable and minimal resource consumption (CPU, memory, threads) for highly-scalable applications.

Make your changes and simply hit refresh! All you need is a browser and a text editor:
- Hit refresh workflow
- Powerful console & build tools
- Type safety
- Built in testing tools
- IDE support for Eclipse and IntelliJ IDEA

Underneath the covers Play uses a fully asynchronous model built on top of Akka. Combined with being stateless, Play scales simply and predictably.
- Stateless Web Tier
- Non-blocking I/O
- Built on Akka
- Real-time enabled

Play was built for needs of modern web & mobile apps.
- RESTful by default
- Asset Compiler for CoffeeScript, LESS, etc
- JSON is a first class citizen
- Websockets, Comet, EventSource
- Extensive NoSQL & Big Data Support

Solid & fast. The compiler and runtime (JVM) do the heavy lifting so that your apps run super-fast and keeps running under load.
- Code is compiled
- Runs on the JVM
- Java NIO via Netty

Massive ecosystem.

The ecosystem around Java is huge. There are libraries for everything - most of which can be used in Play.
- Use Maven Central libraries
- Numerous Play plugins
- Very active Play community

Proven in production.

From startups to enterprises, Play powers some of the most innovative web sites. Play is proven, reliable and scalable.
- Production support by Typesafe
- Many cloud deployment options
- Used in mission-critical apps
